backend/config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]
  resource :map, only: [:show]

  get 'dumb_room/show'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server => "/cable"
  root to: "sessions#new"
end

backend/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

backend/app/models/bomb.rb
class Bomb < ApplicationRecord
  belongs_to :person
  after_create_commit { BombJob.perform_later(self) }

  def position
    return {"lat": self.lat, "lng": self.lng}
  end
end

backend/app/models/dumb.rb
class Dumb < ApplicationRecord
end

backend/app/models/person.rb
class Person < ApplicationRecord
  has_many :bombs, :dependent => :nullify
  before_destroy { PersonJob.perform_later(self, "died") }
  after_save { PersonJob.perform_later(self, "positioned") }

  def in_range?(_lat, _lng, _radius)
    return (self.lat-_lat) ** 2 + (self.lng-_lng) ** 2 < _radius ** 2
  end

  def position
    return {"lat": lat, "lng": lng}
  end
  
end

backend/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  protect_from_forgery with: :exception
end

backend/app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :ensure_authenticated_user
  end

  private
    def ensure_authenticated_user
      authenticate_user(cookies.signed[:user_id]) || redirect_to(new_session_url)
    end

    def authenticate_user(user_id)
      if authenticated_user = Person.find_by(id: user_id)
        cookies.signed[:user_id] ||= user_id
        @current_user = authenticated_user
      end
    end

    def unauthenticate_user
      ActionCable.server.disconnect(current_user: @current_user)
      Person.delete(@current_user)
      @current_user = nil
      cookies.delete(:user_id)
    end
end

backend/app/controllers/dumb_room_controller.rb
class DumbRoomController < ApplicationController
  def show
    @dumbs = Dumb.all
  end
end

backend/app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def show
    @people = Person.all
    @bombs = Bomb.all
  end
end

backend/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_authenticated_user, only: %i( new create )

  def new

  end

  def create
    lat, lng = get_geolocation
    person = Person.create!(lat: lat, lng: lng)
    authenticate_user(person.id)
    redirect_to map_url
  end

  def destroy
    unauthenticate_user
    redirect_to new_session_url
  end

  private
  def get_geolocation
    # TODO, but not very urgent
    fake_location = [100.0, 100.0]
    return fake_location
  end
end

backend/app/helpers/application_helper.rb
module ApplicationHelper
end

backend/app/helpers/dumb_room_helper.rb
module DumbRoomHelper
end

backend/app/helpers/maps_helper.rb
module MapsHelper
end

backend/app/helpers/sessions_helper.rb
module SessionsHelper
end

backend/app/views/dumb_room/show.html.erb
<h1>Dumb room!</h1>
<div id="dumb_room">
  <%= render @dumbs %>
</div>

<form>
  <label>Say sth</label><br>
  <input type="text" data-behavior="dumb_speaker">
</form>

backend/app/views/dumbs/_dumb.html.erb
<div class="dumb">
  <%= dumb.content %>
</div>

backend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Backend</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

backend/app/views/maps/show.html.erb
<%= link_to "Logout", session_url(@current_user.id), method: :delete %>

<style type="text/css">
	html, body { height: 100%; margin: 0; padding: 0; }
	#map { height: 95%; }
	#debug-block { height: 5%; }
</style>

<div id="map"></div>
<div id="debug-block"></div>

<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAL2I2y5jDE4x4_Z2TjbXaUuPzxa1WjxEM&libraries=geometry&callback=initMap"></script>